{"name": "Попытка входа с неверными email и паролем", "status": "passed", "description": "Тест авторизации с неверными учетными данными", "steps": [{"name": "Отправка запроса на авторизацию с неверными данными", "status": "passed", "start": 1741316092801, "stop": 1741316093622}, {"name": "Проверка кода ответа", "status": "passed", "start": 1741316093622, "stop": 1741316093622}, {"name": "Проверка сообщения об ошибке", "status": "passed", "start": 1741316093622, "stop": 1741316093622}], "start": 1741316092801, "stop": 1741316093622, "uuid": "05124994-54a2-41ad-9bfd-9be9f5e4ee0d", "historyId": "74e650c19553433de41dd917b55c6768", "testCaseId": "74e650c19553433de41dd917b55c6768", "fullName": "tests.test_auth.TestAuthLoginEndpoint#test_login_invalid_credentials", "labels": [{"name": "story", "value": "Авторизация с неверными учетными данными"}, {"name": "epic", "value": "Авторизация"}, {"name": "feature", "value": "Вход в систему"}, {"name": "severity", "value": "critical"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthLoginEndpoint"}, {"name": "host", "value": "DESKTOP-UNG0SPG"}, {"name": "thread", "value": "35156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}