{"name": "Попытка входа с неверными email и паролем", "status": "passed", "description": "Тест авторизации с неверными учетными данными", "steps": [{"name": "Отправка запроса на авторизацию с неверными данными", "status": "passed", "start": 1739415400699, "stop": 1739415401435}, {"name": "Проверка кода ответа", "status": "passed", "start": 1739415401435, "stop": 1739415401435}, {"name": "Проверка сообщения об ошибке", "status": "passed", "start": 1739415401435, "stop": 1739415401435}], "start": 1739415400699, "stop": 1739415401435, "uuid": "86a81dfc-4049-411d-adc0-93413bc8fc2b", "historyId": "74e650c19553433de41dd917b55c6768", "testCaseId": "74e650c19553433de41dd917b55c6768", "fullName": "tests.test_auth.TestAuthLoginEndpoint#test_login_invalid_credentials", "labels": [{"name": "story", "value": "Авторизация с неверными учетными данными"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "Вход в систему"}, {"name": "epic", "value": "Авторизация"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestAuthLoginEndpoint"}, {"name": "host", "value": "DESKTOP-UNG0SPG"}, {"name": "thread", "value": "43156-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_auth"}]}